@baseUrl = http://localhost:3000
@contentType = application/json

### Creación de un nuevo usuario
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "nombre": "ADMIN",
  "email": "admin@gmail.com",
  "password": "123",
  "rol": "ADMIN"
}

### Iniciar sesión (login)
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@gmail.com",
  "password": "123"
}

### Obtener usuario actual (requiere estar autenticado)
GET {{baseUrl}}/api/auth/me
Content-Type: {{contentType}}

### Cerrar sesión
POST {{baseUrl}}/api/auth/logout
Content-Type: {{contentType}}

### Actualizar rol de usuario (requiere ser admin)
PUT {{baseUrl}}/api/users/update-role
Content-Type: {{contentType}}

{
  "userId": 2,
  "newRole": "STAFF"
}

### Obtener todos los usuarios (requiere ser admin)
GET {{baseUrl}}/api/users
Content-Type: {{contentType}}