@baseUrl = http://localhost:3000
@contentType = application/json

### Creación de un nuevo usuario
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "nombre": "Usuario Prueba",
  "email": "usuario@ejemplo.com",
  "password": "contraseña123",
  "rol": "FINAL"
}

### Iniciar sesión (login)
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "usuario@ejemplo.com",
  "password": "contraseña123"
}

### Obtener usuario actual (requiere estar autenticado)
GET {{baseUrl}}/api/auth/me
Content-Type: {{contentType}}

### Cerrar sesión
POST {{baseUrl}}/api/auth/logout
Content-Type: {{contentType}}

